### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Eden333** [Leayal/PSO2-Launcher-CSharp#1]
Hi, I was wondering if there is a way to reach you, it seems your old DiscordTag doesn't work anymore.

**Comment by Leayal** [comment]
It's still the same, though?
Or you mean that you can find the Discord User but you can't send messages to?

**Comment by Eden333** [comment]
> It's still the same, though? Or you mean that you can find the Discord User but you can't send messages to?

I cannot find the user
It has probably to do with the space in your name
I can see your account with "NotSoBot" but cannot add it or send a msg

**Comment by Leayal** [comment]
`NotSoBot` is definitely **not** me.
`Dramiel Leayal#8799` so the visible name should be `Dramiel Leayal`.

**Comment by Eden333** [comment]
> `NotSoBot` is definitely **not** me. `Dramiel Leayal#8799` so the visible name should be `Dramiel Leayal`.

NotSoBot is a BOT, there is a command where you type: .user [ID]
and you can see someones user data.

All it shows me is this: 
![image](https://user-images.githubusercontent.com/18154402/159342902-6e2ec725-ae49-4aa3-af58-387fbc726e9f.png)

**Comment by Leayal** [comment]
I don't know why your discord client can't find me.
I definitely set `everyone` to `on` for `who can add you as a friend` as well as allowing direct messages.

**Comment by Eden333** [comment]
Add me then
Eden~♡#2724

**Comment by Leayal** [comment]
I've sent the friend request in Discord.
If you see the request and answered it. Please delete this issue as it's not related to the launcher.
If you don't see the request, please re-open this issue.
